---
# Having the dbtier role depend on the postgresql role
# ensures the proper version of PostgreSQL is installed
# prior to the tasks for creating the database and user.
# The postgresql role takes care of the complexity of installing
# the desired PostgreSQL version on the db server, regardless of whether that server is
# running a Debian or RedHat distribution OS.
dependencies:
- role: postgresql
  sudo: True
  postgresql_server: True
  postgresql_debian_pkgs: [ python-psycopg2 ]
  postgresql_redhat_pkgs: [ python-psycopg2 ]
  postgresql_conf:
    listen_addresses: "'*'"
  postgresql_pg_hba_local_postgres_user: True
  postgresql_pg_hba_local_socket: True
  postgresql_pg_hba_local_ipv4: False
  postgresql_pg_hba_local_ipv6: False
  postgresql_pg_hba_conf:
    - host {{ database_name }} {{ database_user }} {{ application_hostname }} md5
    - local {{ database_name }} {{ database_user }} peer

